// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKGS0WRQ5ycqdZNwCsIEdd7lxNNirfDdQ',
    appId: '1:29610771014:web:4bed93b444b663f1a4c047',
    messagingSenderId: '29610771014',
    projectId: 'flutter-firebase-4a0ba',
    authDomain: 'flutter-firebase-4a0ba.firebaseapp.com',
    storageBucket: 'flutter-firebase-4a0ba.appspot.com',
    measurementId: 'G-QFKLQKMG1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsaD9W-wlD6AQp0J3TmQb5WPqkE1yHC9w',
    appId: '1:29610771014:android:89d832e29240a370a4c047',
    messagingSenderId: '29610771014',
    projectId: 'flutter-firebase-4a0ba',
    storageBucket: 'flutter-firebase-4a0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUJ7Mb3osMMGCYEhTxvbg3Kaer1Heb5eo',
    appId: '1:29610771014:ios:a5420e61a5898b71a4c047',
    messagingSenderId: '29610771014',
    projectId: 'flutter-firebase-4a0ba',
    storageBucket: 'flutter-firebase-4a0ba.appspot.com',
    androidClientId: '29610771014-06hmpcj58cmirsgifbm4ph9fu4kj8abi.apps.googleusercontent.com',
    iosClientId: '29610771014-mg3pl6cp7ud62m4g41u39cntjcm3dasi.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUJ7Mb3osMMGCYEhTxvbg3Kaer1Heb5eo',
    appId: '1:29610771014:ios:fee53e49ed9739a4a4c047',
    messagingSenderId: '29610771014',
    projectId: 'flutter-firebase-4a0ba',
    storageBucket: 'flutter-firebase-4a0ba.appspot.com',
    androidClientId: '29610771014-06hmpcj58cmirsgifbm4ph9fu4kj8abi.apps.googleusercontent.com',
    iosClientId: '29610771014-v2g8klb6j8ncbii70agh0ink1pl8fehu.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
